name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  OS2BORGERPC_VERSION: ''
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: echo
      run: |
        pwd && ls
        env
      
    - name: Checkout
      uses: actions/checkout@v3.5.2
      with:
        repository: OS2borgerPC/admin-site
        fetch-depth: 0

    - name: checkout tag
      run: |
        latesttag=$(git describe --tags --abbrev=0)
        echo checking out ${latesttag}
        git checkout tags/${latesttag}
        echo "LATEST_TAG=${latesttag}" >> "$GITHUB_ENV"
    
    - name: echo
      run: |
        pwd && ls
        git status
        env
        
    # Login to docker hub using secrets in GitHub.
    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: docker/Dockerfile
        tags: kvalitetsit/os2borgerpc-admin:${{ env.LATEST_TAG }}
        push: true
    
